services:
  antithesis-whisper:
    build: 
        context: ../
        dockerfile: whisper/Dockerfile
        tags:
          - ${REPOSITORY}/antithesis-whisper:latest
    image: ${REPOSITORY}/antithesis-whisper:latest
    container_name: antithesis-whisper
    hostname: antithesis-whisper
    command: ["python3", "-u", "main.py"]